# Generated by Django 4.0.1 on 2022-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_trip_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='searchingGender',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
