# Generated by Django 4.0.1 on 2022-03-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='languages',
        ),
    ]
