# Generated by Django 4.0.1 on 2022-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
